management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  shutdown: graceful
  port: 8081
spring:
  profiles:
    active: k8s
  lifecycle:
    timeout-per-shutdown-phase: 20s
  redis:
    port: 6379
    host: localhost
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/k8s
    username: k8s
    password:
  flyway:
    url: jdbc:postgresql://localhost:5432/k8s
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true




shelf: books
