apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-boot-admin-sa
  labels:
    app: spring-boot-admin
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-boot-admin-role
  labels:
    app: spring-boot-admin
    namespace: ecostanzi
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-boot-admin-role-binding
  namespace: ecostanzi
  labels:
    app: spring-boot-admin
subjects:
  - kind: ServiceAccount
    name: spring-boot-admin-sa
    namespace: ecostanzi
roleRef:
  kind: Role
  name: spring-boot-admin-role
  apiGroup: rbac.authorization.k8s.io
