apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-staging

resources:
  - infra
  - apps

images:
  - name: docker.io/enricocostanzi/productservice
    newTag: 1.3.2
  - name: docker.io/enricocostanzi/orderservice
    newTag: 1.5.3
  - name: docker.io/enricocostanzi/adminserver
    newTag: 1.2.2
  - name: redis
    newTag: 6.0.4


commonLabels:
  owner: ecostanzi
  type: ecommerce
  env: staging
