apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: docker.io/enricocostanzi/orderservice:1.0.0
          ports:
           - containerPort: 8080
          env:
            - name: PRODUCT-ENDPOINT
              value: http://product-service
          resources:
            requests: # will only schedule it on a node that can give it that resource
              memory: "100Mi"
              cpu: "250m" # 1/4 core
#            limits: # make sure a container never goes above a certain value
#              memory: "200Mi"
#              cpu: "1000m" # 1 core
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 6
            periodSeconds: 5
          livenessProbe:
              httpGet:
                path: /actuator/health/liveness
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5
