apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: orderservice
    spring-boot: "true"
spec:
  selector:
    app: orderservice
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
