version: '2'
services:
  k8slab-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/<%= baseName %>/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=k8s
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
