apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
  labels:
    app: productservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: docker.io/enricocostanzi/productservice:1.3.2
          ports:
           - containerPort: 8080
          envFrom:
            - configMapRef:
                name: product-configuration
          env:
            - name: SERVER_PORT
              value: '8080'
            - name: SPRING_REDIS_HOST
              value: 'redis-helm-redis-ha.data.svc.cluster.local'
            - name: SPRING_REDIS_PORT
              value: '26379'
            - name: SPRING_R2DBC_URL
              value: 'r2dbc:mysql://mysql:3306/productservice?serverTimezone=UTC'
            - name: SPRING_R2DBC_USERNAME
              value: 'liferay@liferaydb2'
            - name: SPRING_R2DBC_PASSWORD
              value: 'Test@1234'
            - name: SPRING_FLYWAY_URL
              value: 'jdbc:mysql://mysql:3306/productservice?serverTimezone=UTC'
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 6
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
data:
  SHELF: history books
metadata:
  name: product-configuration
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: productservice
    spring-boot: "true"
spec:
  selector:
    app: productservice
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080

