name: Product Microservice Build
on: [push]
#on:
#  push:
#    paths:
#      - product/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-product-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-product
      - name: Product Docker image
        run: |
          ../mvnw package -DskipTests
          mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
        working-directory: product
      - name: get maven version
        run: |
          MVN_VERSION=$(../mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        working-directory: product
#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: enricocostanzi/productservice
#          tag_with_ref: true
#        working-directory: product


