name: Product Microservice Build
on: [push]
#on:
#  push:
#    paths:
#      - product/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-product-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-product
      - name: Unzipping tar to prepare docker image
        run: |
          ../mvnw package -DskipTests
          mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
        working-directory: product
      - name: Estract maven version
        run: |
          echo 'MVN_VERSION<<EOF' >> $GITHUB_ENV
          ../mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        working-directory: product
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: debug
        run: echo $MVN_VERSION
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./product
          push: true
          file: ./product/Dockerfile
          tags: enricocostanzi/productservice:${MVN_VERSION}


